---
kind: pipeline
type: vm
name: docker-buildx

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

  - name: Docker Build
    image: plugins/docker
    settings:
      repo: cube8021/docker-buildx
      tags:
      - latest
      - ${DRONE_BUILD_NUMBER}
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
      dockerfile: Dockerfile
      context: .
      pull: true
      dry_run: false
      daemon_off: true
      no_cache: false
      squash: false
      purge: false
      insecure: false
      auto_tag: false
      auto_tag_suffix: latest
      registry: https://index.docker.io/v1/